Mark = []

m1 = int(input("Enter your mark: "))
Mark.append(m1)
m2 = int(input("Enter your mark: "))
Mark.append(m2)
m3 = int(input("Enter your mark: "))
Mark.append(m3)
m4 = int(input("Enter your mark: "))
Mark.append(m4)
m5 = int(input("Enter your mark: "))
Mark.append(m5)
m6 = int(input("Enter your mark: "))
Mark.append(m6)
m7 = int(input("Enter your mark: "))
Mark.append(m7)
Mark.sort()
print(Mark)
print(type(Mark))